# Generated by Django 4.1.5 on 2023-01-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApiApp', '0005_album_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
